title: <p align="center"> Amir Fakhim </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/amir-fakhim/">LinkedIn</a> |
  <a href="https://github.com/amirfakhim">GitHub</a>
  </p>
  
  <p align="justify">
  I’m a machine-learning and AI enthusiast interested in Time-series analysis, Recommender systems, Computer vision, and NLP.
  <br><br>
  I’m looking to collaborate on data science projects.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-G2H8NGKMN0 # Google Analytics tracking ID
